class twoSum {
    public static int [] main(int[] nums, int target){
     int [] result = new int[2];
        for (int i = 0; 1 <nums.length; i++){
            for (int j = 0; 1 < nums.length +1; i++){
                if (numbs[i] + nums[j]== target){
                    result[0] = i;
                    result[1] = j;
                    return [i,j];
                }
            }
        }
    }
}